# Serverless Configuration File

service: see-this-and-drink-water-telegram-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}

functions:
  cron:
    handler: app.handler.send_message
    events:
      # Invoke Lambda function at 10:00 - 21:00 (UTC+8) every
      # Syntax reference: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents-expressions.html
      - schedule: cron(00 2-13 * * ? *)

package:
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - '!**/__pycache__/**'
    - '!.github/**'
    - '!.editorconfig'
    - '!.nvmrc'

# Handling python packages: https://www.serverless.com/blog/serverless-python-packaging
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

